### ISSUE TITLE
Velum on Kubic

### ISSUE THREAD

**Issue by PI-Victor** [kubic-project/community#3]
From the previous issue:
> Hi, how can I activate the Velum dashboard in Kubic?
 
https://github.com/kubic-project/velum/issues/216

**Comment by PI-Victor** [comment]
@tgeek77 the current image is not loading velum because i can't see any manifests in /etc/kubernetes/manifests. kubelet is supposed to load them and start the salt-api, dashboard and db - but i'm not 100% sure how this would work on kubic, so i might be wrong.
the docker images are installed via rpms and loaded with `container-feeder` in the docker daemon. but i cannot see that on kubic.
 will try to find out tomorrow and open a bugzilla if it's an actual issue.

**Comment by thkukuk** [comment]
On Wed, Jul 05, Ionuț Victor Palade wrote:

> @tgeek77 the current image is not loading velum because i can't see any
> manifests in /etc/kubernetes/manifests. kubelet is supposed to load them and
> start the salt-api, dashboard and db - but i'm not 100% sure how this would
> work on kubic, so i might be wrong.

As told the in the presentation, the containers including velum are still
missing on Kubik, since they are not yet part of Factory/Tumbleweed.

-- 
Thorsten Kukuk, Distinguished Engineer, Senior Architect SLES & CaaSP
SUSE LINUX GmbH, Maxfeldstr. 5, 90409 Nuernberg, Germany
GF: Felix Imendoerffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nuernberg)

**Comment by PI-Victor** [comment]
ah, i remember now.

**Comment by tgeek77** [comment]
Thanks guys, I'll keep an eye on the newest builds and be patient.

**Comment by suntorytimed** [comment]
Any news on the Velum container?

**Comment by suntorytimed** [comment]
Already found more recent information on Bugzilla. Here is the link to the Bugzilla bug https://bugzilla.opensuse.org/show_bug.cgi?id=1058919

**Comment by thkukuk** [comment]
On Mon, Nov 13, Stefan Weiberg wrote:

> Already found more recent information on Bugzilla. Here is the link to the
> Bugzilla bug https://bugzilla.opensuse.org/show_bug.cgi?id=1058919

We have containers in a devel project:
https://build.opensuse.org/project/monitor/devel:CaaSP:kubic-container

We have images using this containers:
https://build.opensuse.org/project/monitor/devel:CaaSP:1.0

But, somebody needs to port velum to ruby 2.5 and fix the bootstrap
problems with generating certificates, at minimum.
