### ISSUE TITLE
Kubic Doesn't install in VMWare

### ISSUE THREAD

**Issue by PI-Victor** [kubic-project/community#4]
There seems to be a generic issue reported by multiple members.
https://github.com/kubic-project/caasp-devenv/issues/10
> Not sure if this is a proper place to post,
According to the SUSE caasp-beta team, their mailing list and other "support" don't support Kubic which is considered separate and "community."
And, I can't find a project or repository specifically for the Kubic ISO.
Also, unable to find an OBS project for Kubic (although my search capability may be poor).

> So, I cannot find any Kubic support or reporting places except this github Kubic project as a whole.
> The Kubic ISO install results in only a partial install and boots only into Recovery Mode without networking.
    Lack of documentation, in particular just for initial deployment, configuration and updating. In particular, it should be no surprise the transactional-update command is new to me, I don't know if repos need to be configured (or how). There is no MAN page or sufficient "--help" to get it to work, or is it supposed to automatically point to SUSE caasp-beta repos? But, even if this is better addressed, I assume that this requires a working networking connection.

> TIA,
> Tony

The other issue reported can be found here, together with the .tar file of the logs and other info.

https://github.com/kubic-project/e2e-tests/issues/46

I've squashed these together since they address the same problem.

**Comment by tgeek77** [comment]
This isn't the case anymore for me with the current build of Kubic

**Comment by PI-Victor** [comment]
@tgeek77 that's good to hear. didn't try to install vmware. only on kvm/qemu and it works for me.
@putztzu to answer some of your questions - 

for opening bugs, see the [Kubic -Tumbleweed Bugzilla](https://bugzilla.opensuse.org/buglist.cgi?component=Kubic&list_id=7052689&product=openSUSE%20Tumbleweed&resolution=---) mentioned on the readme of this repo.
Also docs and more information will be coming soon to this repo
