### ISSUE TITLE
Kubic install fails with 20170825 media

### ISSUE THREAD

**Issue by pgonin** [kubic-project/community#7]
http://download.opensuse.org/tumbleweed/iso/openSUSE-Tumbleweed-Kubic-DVD-x86_64-Current.iso

![screenshot_opensusetumbleweed_2017-08-29_14 00 59](https://user-images.githubusercontent.com/6192686/29819879-c792be68-8cc2-11e7-9a20-8b668387bac6.png)

**Comment by thkukuk** [comment]
Bugzilla is still the tool for reporting bugs for the openSUSE Kubic media, this hasn't changed.

**Comment by pgonin** [comment]
sure, but on openSUSE bugzilla I was offered to report on the following products:

Backports / openSUSE Backports
Distribution / openSUSE Leap & Stable releases
Tumbleweed / openSUSE Rolling Release
openSUSE.org / The openSUSE project (not the distribution)

I looked further and realized I can report on Tumbleweed product with kubic component.
Not intuitive, but now will do there.
